# Generated by Django 6.0.4 on 2026-05-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_trainer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="trainer",
        ),
    ]
