# Generated by Django 6.0.4 on 2026-05-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_course_trainer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="youtube_link",
        ),
    ]
