# Generated by Django 6.0.4 on 2026-05-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_enrollmentrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursevideo",
            name="youtube_link",
            field=models.CharField(max_length=100),
        ),
    ]
